config/routes.rb
Rails.application.routes.draw do
  root to: "orders#index"
  devise_for :vendors
  resources :customers
  resources :products
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  phone      :string
#  vendor_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ApplicationRecord
  validates :name, :email, :phone, presence: true

  belongs_to :vendor
  has_many :orders
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :integer          not null, primary key
#  total       :decimal(, )
#  subtotal    :decimal(, )
#  iva         :decimal(, )
#  vendor_id   :integer
#  customer_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Order < ApplicationRecord
  belongs_to :vendor
  belongs_to :customer
  has_and_belongs_to_many :products, dependent: :destroy


  def sumatoria
     suma = 0
     self.products.each do |product|
       suma = suma + product.price
     end
     self.update(subtotal: suma)
     self.update(iva: self.subtotal * 0.19)
     self.update(total: self.subtotal + self.iva)
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  width      :integer
#  height     :integer
#  unit       :decimal(, )
#  quantity   :integer
#  price      :decimal(, )
#  code       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ApplicationRecord
  validates :width, :height, :unit, :quantity, presence: true

  has_and_belongs_to_many :orders, dependent: :destroy
end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#

class Vendor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :destroy]
  before_action :authenticate_vendor!, except: [:index]

    def index
      @customers = Customer.all.order(created_at: :desc)
    end

    def new
      @customer = Customer.new
    end

    def create
      @customer = Customer.create(customer_params)
      @customer.vendor = current_vendor
      if @customer.save
        redirect_to customers_path, notice: 'Cliente creado correctamente.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @customer.update(customer_params)
        redirect_to customers_path, notice: 'Cliente editado correctamente.'
      else
        render :edit
      end
    end

    def destroy
      @customer.destroy
      redirect_to customers_path, notice: 'Cliente eliminado correctamente.'
    end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email, :phone, :vendor_id)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_vendor!, except: [:index, :show]

    def index
      @orders = Order.all.order(created_at: :desc)
    end

    def new
      @order = Order.new
    end

    def create
      @order = Order.new(order_params)
      @order.vendor = current_vendor
      @order.sumatoria
      if @order.save
        redirect_to orders_path, notice: 'Pedido creado correctamente.'
      else
        render :new
      end
    end

    def show

    end

    def edit
    end

    def update
      if @order.update(order_params)
        @order.sumatoria
        redirect_to orders_path, notice: 'Pedido editado correctamente.'
      else
        render :edit
      end
    end

    def destroy
      @order.destroy
      redirect_to orders_path, notice: 'Pedido eliminado correctamente.'
    end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:total, :subtotal, :iva, :vendor_id, :customer_id, product_ids:[])
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :authenticate_vendor!, except: [:index]

    def index
      @products = Product.all.order(created_at: :desc)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to products_path, notice: 'Producto creado correctamente.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @product.update(product_params)
        redirect_to products_path, notice: 'Producto editado correctamente.'
      else
        render :edit
      end
    end

    def destroy
      @product.destroy
      redirect_to products_path, notice: 'Producto eliminado correctamente.'
    end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:width, :height, :unit, :quantity, :price, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_msg(key)
    case key
     when 'notice' then 'alert alert-info'
     when 'success' then 'alert alert-success'
     when 'error' then 'alert alert-danger'
     when 'alert' then 'alert alert-warning'
   end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def form_title_customer
    @customer.new_record? ? "Crear Cliente" : "Editar Cliente"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def form_title_order
    @order.new_record? ? "Crear Pedido" : "Editar Pedido"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_title_product
    @product.new_record? ? "Crear Producto" : "Editar Producto"
  end
end

app/views/customers/_form.html.erb
<div id="customer-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= form_title_customer %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <%= form_for @customer, remote: true do |f| %>
        <div class="modal-body">

          <% if @customer.errors.any? %>
            <div class="alert alert-danger">
              <ul>
              <% @customer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "Cliente" %>
          </div>

          <div class="form-group">
            <%= f.text_field :email, class: "form-control input-lg", placeholder: "Email" %>
          </div>

          <div class="form-group">
            <%= f.text_field :phone, class: "form-control input-lg", placeholder: "Tel/Cel" %>
          </div>
        </div>

        <div class="modal-footer">
          <%= f.submit form_title_customer, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/customers/_row.html.erb
<tr id="<%= customer.id %>">
  <td><%= customer.name %></td>
  <td><%= customer.email %></td>
  <td><%= customer.phone %></td>
  <td>
    <% if vendor_signed_in? && current_vendor.id == customer.vendor_id  %>
      <span class="metric-value">
        <%= link_to "", edit_customer_path(customer), remote: true, class: "fas fa-edit mr-1"%>
      </span>
    <% end %>
  </td>
</tr>

app/views/customers/index.html.erb
<div class="container my-5">
  <div class="row justify-content-between">
    <h2 class= "font-weight-bold">Clientes</h2>
    <% if vendor_signed_in? %>
    <span class="d-flex justify-content-end">
      <%= link_to 'Nuevo Cliente', new_customer_path, remote: true, class:"btn btn-primary" %>
    </span>
    <% end %>
  </div>
  <div class="row my-5">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Tel/Cel</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <%= render "row", customer: customer %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% flash.each do |key, msg| %>
  <div class="<%= flash_msg(key) %>">
    <%=msg%>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <span class="navbar-brand"><%= link_to "X-Bolsas", orders_path, class: "text-white font-weight-bold" %></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
    		<li class="nav-link"><%= link_to "Clientes", customers_path, class: "text-white"%></li>
    		<li class="nav-link"><%= link_to "Productos", products_path, class: "text-white"%></li>
    		<li class="nav-link"><%= link_to "Pedidos", orders_path, class: "text-white"%></li>
      </ul>
      <%= render 'layouts/vendor_signed' %>
    </div>

  </div>
</nav>

app/views/layouts/_vendor_signed.html.erb
<% if vendor_signed_in? %>
	<ul class="navbar-nav ml-auto">
		<li class="nav-link"><%= link_to "Salir", destroy_vendor_session_path, method: :delete, class: "text-white" %></li>
  </ul>
<% else %>
	<ul class="navbar-nav ml-auto">
  	<li class="nav-link"><%= link_to "Ingresar", new_vendor_session_path, class: "text-white" %></li>
  	<li class="nav-link"><%= link_to "Registrarse", new_vendor_registration_path, class: "text-white" %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xbolsas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <script>
      $(".alert").fadeIn(500).css("opacity", "0.85").delay(5000).slideUp(900);
    </script>
  </body>
</html>

app/views/orders/_form.html.erb
<div id="order-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= form_title_order %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <%= form_for @order, remote: true do |f| %>
        <div class="modal-body">

          <% if @order.errors.any? %>
            <div class="alert alert-danger">
              <ul>
              <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="alert alert-danger" role="alert" style="display: none;"></div>

          <div class="form-group">
            <%= f.collection_select :customer_id, Customer.all, :id, :name, {:prompt => 'Seleccione un Cliente'} %>
          </div>
          <hr>
          <div class="form-group">

            <h3>Productos</h3>
            <%= f.collection_check_boxes(:product_ids, Product.all, :id, :code) do |b| %>
             <%= b.label class:"label-checkbox mr-4" do %>
               <%=b.check_box%>
               <%=b.text%>
              <% end %>
            <% end %>
          </div>
        <%= current_vendor.name %>
        <div class="modal-footer">

          <%= f.submit form_title_order, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/orders/_row.html.erb
<tr id="<%= order.id %>">
  <td><%= order.vendor.name %></td>
  <td><%= order.customer.name %></td>
  <td><%= number_to_currency(order.subtotal, precision: 0) %></td>
  <td><%= number_to_currency(order.iva, precision: 0) %></td>
  <td>
    <%= number_to_currency(order.total, precision: 0) %>
    <%= link_to "", order_path(order), class: "fas fa-info-circle mr-1 float-right" %>
  </td>
  <td>
    <% if vendor_signed_in? && current_vendor.id == order.vendor_id %>
      <span class="metric-value">
        <%= link_to "", edit_order_path(order), remote: true, class: "fas fa-edit mr-1"%>
        <%= link_to "", order, class: "fas fa-trash-alt mr-1", method: :delete, data: { confirm: 'Desea eliminar el Pedido?' }  %>
      </span>
    <% end %>
  </td>
</tr>

app/views/orders/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/orders/index.html.erb
<div class="container my-5">
  <div class="row justify-content-between">
    <h2 class= "font-weight-bold">Pedidos</h2>
    <% if vendor_signed_in? %>
      <span class="d-flex justify-content-end">
        <%= link_to 'Nuevo Pedido', new_order_path, remote: true, class:"btn btn-primary" %>
      </span>
    <% end %>
  </div>
  <div class="row my-5">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th>Subtotal</th>
            <th>Iva</th>
            <th>Total</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <%= render "row", order: order %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/orders/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/orders/show.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="card" style="width: 60%;">
      <div class="card-header text-center">
        <%= @order.customer.name %>
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <table class="table table-hover my-3">
            <thead class="thead">
              <tr class="text-center">
                <th scope="col-4">Producto(s)</th>
                <th scope="col-3">Valor</th>
              </tr>
            </thead>
            <tbody>
                <tr style="height: 15em;">
                  <td class="metric col-4">
                    <ul>
                      <% @order.products.each do |order| %>
                        <li>
                          <%= order.code  %>
                        </li>
                      <% end %>
                    </ul>
                  </td>

                  <td class="metric col-3 text-center">
                    <ul>
                      <% @order.products.each do |order| %>
                        <li>
                          <%= number_to_currency(order.price, precision: 0) %>
                        </li>
                      <% end %>
                    </ul>
                  </td>
                </tr>

                <tr>
                  <td class="metric col-4">
                    SUBTOTAL
                  </td>

                  <td class="metric col-3 text-center">
                    <%= number_to_currency(@order.subtotal, precision: 0) %>
                  </td>
                </tr>

                <tr>
                  <td class="metric col-4">
                    IVA
                  </td>

                  <td class="metric col-3 text-center">
                    <%= number_to_currency(@order.iva, precision: 0) %>
                  </td>
                </tr>

                <tr>
                  <td class="metric col-4">
                    TOTAL
                  </td>

                  <td class="metric col-3 text-center bg-info">
                    <%= number_to_currency(@order.total, precision: 0) %>
                  </td>
                </tr>
            </tbody>
          </table>
          <footer class="blockquote-footer"><%= @order.vendor.name %></footer>
          <% if vendor_signed_in? && current_vendor.id == @order.vendor_id  %>
            <span class="metric-value float-right">
              <%= link_to "", edit_order_path(@order), class: "fas fa-edit mr-1"%>
              <%= link_to "", @order, class: "fas fa-trash-alt mr-1", method: :delete, data: { confirm: 'Desea eliminar el Pedido?' }  %>
            </span>
          <% end %>
        </blockquote>
      </div>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= form_title_product %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <%= form_for @product, remote: true do |f| %>
        <div class="modal-body">

          <% if @product.errors.any? %>
            <div class="alert alert-danger">
              <ul>
              <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <%= f.text_field :width, class: "form-control input-lg", placeholder: "Ancho" %>
          </div>

          <div class="form-group">
            <%= f.text_field :height, class: "form-control input-lg", placeholder: "Alto" %>
          </div>

          <div class="form-group">
            <%= f.text_field :unit, class: "form-control input-lg", placeholder: "Valor Unidad" %>
          </div>

          <div class="form-group">
            <%= f.text_field :quantity, class: "form-control input-lg", placeholder: "Cantidad" %>
          </div>
        </div>

        <div class="modal-footer">
          <%= f.submit form_title_product, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/products/_row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.code %></td>
  <td><%= product.width %></td>
  <td><%= product.height %></td>
  <td><%= number_to_currency(product.unit, precision: 0) %></td>
  <td><%= product.quantity %></td>
  <td><%= number_to_currency(product.price, precision: 0) %></td>
  <td>
    <% if vendor_signed_in? %>
      <span class="metric-value">
        <%= link_to "", edit_product_path(product), remote: true, class: "fas fa-edit mr-1"%>
      </span>
    <% end %>
  </td>
</tr>

app/views/products/index.html.erb
<div class="container my-5">
  <div class="row justify-content-between">
    <h2 class= "font-weight-bold">Productos (Medidas en cm)</h2>
    <% if vendor_signed_in? %>
    <span class="d-flex justify-content-end">
      <%= link_to 'Nuevo Producto', new_product_path, remote: true, class:"btn btn-primary" %>
    </span>
    <% end %>
  </div>
  <div class="row my-5">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Codigo</th>
            <th>Ancho</th>
            <th>Alto</th>
            <th>Valor Unidad</th>
            <th>Cantidad Bolsas</th>
            <th>Precio</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <% product.update code: "B-#{product.width}#{product.height}-#{product.quantity}" %>
            <% product.update price: "#{product.unit * product.quantity}" %>
            <%= render "row", product: product %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>